package com.devops.portal;
import jakarta.servlet.annotation.WebServlet;import jakarta.servlet.http.*;import java.io.*;import java.sql.SQLException;import java.util.*;
@WebServlet("/api/auth/*") public class AuthServlet extends HttpServlet{
 protected void doGet(HttpServletRequest r,HttpServletResponse p)throws IOException{p.setContentType("application/json;charset=UTF-8");Map<String,Object> u=Auth.user(r);if(u==null){json(p,"{\"authenticated\":false}");return;}json(p,"{\"authenticated\":true,\"name\":\""+Json.esc((String)u.get("name"))+"\",\"role\":\""+u.get("role")+"\"}");}
 protected void doPost(HttpServletRequest r,HttpServletResponse p)throws IOException{String path=r.getPathInfo();p.setContentType("application/json;charset=UTF-8");try{if("/register".equals(path)){register(r,p);return;}if("/login".equals(path)){login(r,p);return;}if("/logout".equals(path)){Auth.logout(r);json(p,"{\"ok\":true}");return;}json(p,"{\"ok\":false,\"error\":\"Unknown action\"}");}catch(Exception e){p.setStatus(500);json(p,"{\"ok\":false,\"error\":\"Server error\"}");}}
 private void register(HttpServletRequest r,HttpServletResponse p)throws Exception{String name=trim(r.getParameter("name")),email=trim(r.getParameter("email")),pw=r.getParameter("password"),dept=trim(r.getParameter("department")),year=trim(r.getParameter("year"));if(name.length()<2||email.length()<5||pw==null||pw.length()<8){p.setStatus(400);json(p,"{\"ok\":false,\"error\":\"Use a valid name, email and password of at least 8 characters.\"}");return;}if(Database.findUser(email)!=null){p.setStatus(409);json(p,"{\"ok\":false,\"error\":\"An account with this email already exists.\"}");return;}long id=Database.createUser(name,email,PasswordUtil.hash(pw),dept,year);Map<String,Object> u=Database.findUser(email);u.remove("password_hash");Auth.login(r,u);json(p,"{\"ok\":true,\"role\":\"STUDENT\"}");}
 private void login(HttpServletRequest r,HttpServletResponse p)throws Exception{String email=trim(r.getParameter("email")),pw=r.getParameter("password");Map<String,Object> u=Database.findUser(email);if(u==null||pw==null||!PasswordUtil.verify(pw,(String)u.get("password_hash"))){p.setStatus(401);json(p,"{\"ok\":false,\"error\":\"Invalid email or password.\"}");return;}u.remove("password_hash");Auth.login(r,u);json(p,"{\"ok\":true,\"role\":\""+u.get("role")+"\"}");}
 private static String trim(String s){return s==null?"":s.trim();}private static void json(HttpServletResponse p,String s)throws IOException{p.getWriter().print(s);}
}
