package com.devops.portal;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.sql.*;
import java.util.*;

public final class Database {
    private static String url(){return env("DB_URL","jdbc:h2:file:./data/feedbackhub;AUTO_SERVER=TRUE");}
    private static String user(){return env("DB_USER","sa");}
    private static String pass(){return env("DB_PASSWORD","");}
    private static String env(String k,String d){String v=System.getenv(k);return v==null||v.isBlank()?d:v;}
    static { try { Class.forName(url().startsWith("jdbc:mysql:")?"com.mysql.cj.jdbc.Driver":"org.h2.Driver"); init(); } catch(Exception e){throw new ExceptionInInitializerError(e);} }
    private Database(){}
    public static Connection getConnection() throws SQLException { return DriverManager.getConnection(url(),user(),pass()); }
    private static void init() throws Exception {
        try(Connection c=getConnection(); Statement s=c.createStatement()){
            boolean mysql=url().startsWith("jdbc:mysql:");
            String auto=mysql?"AUTO_INCREMENT":"GENERATED BY DEFAULT AS IDENTITY";
            s.execute("CREATE TABLE IF NOT EXISTS users (id BIGINT "+auto+" PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(180) NOT NULL UNIQUE, password_hash VARCHAR(400) NOT NULL, role VARCHAR(20) NOT NULL DEFAULT 'STUDENT', department VARCHAR(120), year_level VARCHAR(30), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
            s.execute("CREATE TABLE IF NOT EXISTS feedback (id BIGINT "+auto+" PRIMARY KEY, user_id BIGINT NULL, category VARCHAR(60) NOT NULL, title VARCHAR(180) NOT NULL, message VARCHAR(2000) NOT NULL, rating INT NOT NULL, anonymous BOOLEAN NOT NULL DEFAULT FALSE, status VARCHAR(40) NOT NULL DEFAULT 'SUBMITTED', priority VARCHAR(20) NOT NULL DEFAULT 'NORMAL', action_note VARCHAR(1000), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id))");
            s.execute("CREATE INDEX IF NOT EXISTS idx_feedback_status ON feedback(status)"); s.execute("CREATE INDEX IF NOT EXISTS idx_feedback_category ON feedback(category)");
            s.execute("CREATE TABLE IF NOT EXISTS volunteers (id BIGINT "+auto+" PRIMARY KEY, name VARCHAR(120) NOT NULL, surname VARCHAR(120) NOT NULL, mobile VARCHAR(30) NOT NULL, email VARCHAR(180) NOT NULL, gender VARCHAR(30), studying_about VARCHAR(180), description VARCHAR(2000), availability VARCHAR(120), skills VARCHAR(500), status VARCHAR(30) NOT NULL DEFAULT 'NEW', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
            s.execute("CREATE INDEX IF NOT EXISTS idx_volunteer_status ON volunteers(status)");
            try(PreparedStatement p=c.prepareStatement("SELECT COUNT(*) FROM users WHERE role='ADMIN'"); ResultSet r=p.executeQuery()){r.next();if(r.getInt(1)==0){try(PreparedStatement ins=c.prepareStatement("INSERT INTO users(name,email,password_hash,role) VALUES(?,?,?,?)")){ins.setString(1,"System Administrator");ins.setString(2,"admin@feedbackhub.local");ins.setString(3,PasswordUtil.hash("Admin@123"));ins.setString(4,"ADMIN");ins.executeUpdate();}}}
        }
    }
    public static long createUser(String name,String email,String hash,String department,String year) throws SQLException{
        try(Connection c=getConnection();PreparedStatement p=c.prepareStatement("INSERT INTO users(name,email,password_hash,department,year_level) VALUES(?,?,?,?,?)",Statement.RETURN_GENERATED_KEYS)){p.setString(1,name);p.setString(2,email);p.setString(3,hash);p.setString(4,department);p.setString(5,year);p.executeUpdate();try(ResultSet r=p.getGeneratedKeys()){r.next();return r.getLong(1);}}
    }
    public static Map<String,Object> findUser(String email) throws SQLException{try(Connection c=getConnection();PreparedStatement p=c.prepareStatement("SELECT * FROM users WHERE LOWER(email)=LOWER(?)")){p.setString(1,email);try(ResultSet r=p.executeQuery()){if(!r.next())return null;Map<String,Object> m=new HashMap<>();m.put("id",r.getLong("id"));m.put("name",r.getString("name"));m.put("email",r.getString("email"));m.put("password_hash",r.getString("password_hash"));m.put("role",r.getString("role"));m.put("department",r.getString("department"));m.put("year_level",r.getString("year_level"));return m;}}}
    public static long addFeedback(Long uid,String category,String title,String message,int rating,boolean anon) throws SQLException{try(Connection c=getConnection();PreparedStatement p=c.prepareStatement("INSERT INTO feedback(user_id,category,title,message,rating,anonymous) VALUES(?,?,?,?,?,?)",Statement.RETURN_GENERATED_KEYS)){if(uid==null)p.setNull(1,Types.BIGINT);else p.setLong(1,uid);p.setString(2,category);p.setString(3,title);p.setString(4,message);p.setInt(5,rating);p.setBoolean(6,anon);p.executeUpdate();try(ResultSet r=p.getGeneratedKeys()){r.next();return r.getLong(1);}}}
    public static List<Map<String,Object>> feedback(Long userId, boolean admin) throws SQLException{String q=admin?"SELECT f.*,u.name student_name,u.email student_email FROM feedback f LEFT JOIN users u ON f.user_id=u.id ORDER BY f.created_at DESC":"SELECT * FROM feedback WHERE user_id=? ORDER BY created_at DESC";try(Connection c=getConnection();PreparedStatement p=c.prepareStatement(q)){if(!admin)p.setLong(1,userId);try(ResultSet r=p.executeQuery()){List<Map<String,Object>> a=new ArrayList<>();while(r.next()){Map<String,Object> m=new LinkedHashMap<>();for(String k:List.of("id","category","title","message","rating","anonymous","status","priority","action_note","created_at","updated_at"))m.put(k,r.getObject(k));if(admin){m.put("student_name",r.getString("student_name"));m.put("student_email",r.getString("student_email"));}a.add(m);}return a;}}}
    public static Map<String,Object> stats() throws SQLException{Map<String,Object> m=new LinkedHashMap<>();try(Connection c=getConnection();Statement s=c.createStatement()){
        ResultSet r=s.executeQuery("SELECT COUNT(*) total, COALESCE(AVG(rating),0) avg_rating FROM feedback");r.next();m.put("total",r.getInt("total"));m.put("average",r.getDouble("avg_rating"));
        r=s.executeQuery("SELECT COUNT(*) n FROM feedback WHERE status NOT IN ('RESOLVED','CLOSED')");r.next();m.put("open",r.getInt(1));
        r=s.executeQuery("SELECT COUNT(*) n FROM feedback WHERE status='RESOLVED'");r.next();m.put("resolved",r.getInt(1));
        Map<String,Integer> cats=new LinkedHashMap<>();r=s.executeQuery("SELECT category,COUNT(*) n FROM feedback GROUP BY category ORDER BY n DESC");while(r.next())cats.put(r.getString(1),r.getInt(2));m.put("categories",cats);return m;}}

    public static long addVolunteer(String name,String surname,String mobile,String email,String gender,String studying,String description,String availability,String skills) throws SQLException {
        String q="INSERT INTO volunteers(name,surname,mobile,email,gender,studying_about,description,availability,skills) VALUES(?,?,?,?,?,?,?,?,?)";
        try(Connection c=getConnection();PreparedStatement p=c.prepareStatement(q,Statement.RETURN_GENERATED_KEYS)){
            p.setString(1,name);p.setString(2,surname);p.setString(3,mobile);p.setString(4,email);p.setString(5,gender);p.setString(6,studying);p.setString(7,description);p.setString(8,availability);p.setString(9,skills);p.executeUpdate();
            try(ResultSet r=p.getGeneratedKeys()){r.next();return r.getLong(1);}
        }
    }
    public static List<Map<String,Object>> volunteers() throws SQLException {
        try(Connection c=getConnection();Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT * FROM volunteers ORDER BY created_at DESC")){
            List<Map<String,Object>> out=new ArrayList<>();
            while(r.next()){Map<String,Object> m=new LinkedHashMap<>(); for(String k:List.of("id","name","surname","mobile","email","gender","studying_about","description","availability","skills","status","created_at")) m.put(k,r.getObject(k)); out.add(m);} return out;
        }
    }
    public static void updateVolunteer(long id,String status) throws SQLException {try(Connection c=getConnection();PreparedStatement p=c.prepareStatement("UPDATE volunteers SET status=? WHERE id=?")){p.setString(1,status);p.setLong(2,id);p.executeUpdate();}}

    public static void updateFeedback(long id,String status,String priority,String note) throws SQLException{try(Connection c=getConnection();PreparedStatement p=c.prepareStatement("UPDATE feedback SET status=?,priority=?,action_note=?,updated_at=CURRENT_TIMESTAMP WHERE id=?")){p.setString(1,status);p.setString(2,priority);p.setString(3,note);p.setLong(4,id);p.executeUpdate();}}
}
