CREATE DATABASE IF NOT EXISTS feedbackhub CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE feedbackhub;
CREATE TABLE IF NOT EXISTS users (id BIGINT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(120) NOT NULL,email VARCHAR(180) NOT NULL UNIQUE,password_hash VARCHAR(400) NOT NULL,role VARCHAR(20) NOT NULL DEFAULT 'STUDENT',department VARCHAR(120),year_level VARCHAR(30),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS feedback (id BIGINT PRIMARY KEY AUTO_INCREMENT,user_id BIGINT NULL,category VARCHAR(60) NOT NULL,title VARCHAR(180) NOT NULL,message VARCHAR(2000) NOT NULL,rating INT NOT NULL,anonymous BOOLEAN NOT NULL DEFAULT FALSE,status VARCHAR(40) NOT NULL DEFAULT 'SUBMITTED',priority VARCHAR(20) NOT NULL DEFAULT 'NORMAL',action_note VARCHAR(1000),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE INDEX idx_feedback_status ON feedback(status);
CREATE INDEX idx_feedback_category ON feedback(category);


CREATE TABLE IF NOT EXISTS volunteers (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(120) NOT NULL, surname VARCHAR(120) NOT NULL,
 mobile VARCHAR(30) NOT NULL, email VARCHAR(180) NOT NULL, gender VARCHAR(30), studying_about VARCHAR(180) NOT NULL,
 description VARCHAR(2000) NOT NULL, availability VARCHAR(120), skills VARCHAR(500), status VARCHAR(30) NOT NULL DEFAULT 'NEW',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_volunteer_status ON volunteers(status);
